# Generated by Django 4.2.1 on 2023-07-25 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselingType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CounseleeList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('counselee', models.ForeignKey(db_column='counselee', on_delete=django.db.models.deletion.CASCADE, related_name='list_counselee', to='accounts.counselee')),
                ('counselor', models.ForeignKey(db_column='counselor', on_delete=django.db.models.deletion.CASCADE, related_name='list_counselor', to='accounts.counselor')),
            ],
        ),
    ]
