# Generated by Django 4.2.1 on 2023-06-18 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_social_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="counselee",
            name="userkey",
            field=models.ForeignKey(
                db_column="userkey",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="counselee_id",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="counselor",
            name="userkey",
            field=models.ForeignKey(
                db_column="userkey",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="counselor_id",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
