# Generated by Django 4.2.1 on 2023-06-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_counselor_counselee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='counselor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
