# Generated by Django 4.2.1 on 2023-08-03 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='counselor',
            name='credit',
            field=models.CharField(default='1-001', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counselor',
            name='institution_address',
            field=models.CharField(default='서울시 도봉구', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counselor',
            name='institution_name',
            field=models.CharField(default='심리상담소', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counselor',
            name='prof_field',
            field=models.ForeignKey(db_column='prof_field', default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.counselingtype'),
            preserve_default=False,
        ),
    ]
