# Generated by Django 4.2.1 on 2023-06-18 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_alter_counselee_userkey_alter_counselor_userkey"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "time",
                    models.CharField(
                        choices=[
                            ("09:00", "1"),
                            ("10:00", "2"),
                            ("11:00", "3"),
                            ("12:00", "4"),
                            ("13:00", "5"),
                            ("14:00", "6"),
                            ("15:00", "7"),
                            ("16:00", "8"),
                            ("17:00", "9"),
                            ("18:00", "10"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("대인관계", "대인관계"),
                            ("외로움", "외로움"),
                            ("부정적 사고방식", "부정적 사고방식"),
                            ("자존감 하락", "자존감 하락"),
                            ("불면증", "불면증"),
                            ("알코올 의존증", "알코올 의존증"),
                            ("기타", "기타"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "counselee_id",
                    models.ForeignKey(
                        db_column="counselee_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.counselee",
                    ),
                ),
                (
                    "counselor_id",
                    models.ForeignKey(
                        db_column="counselor_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.counselor",
                    ),
                ),
            ],
        ),
    ]
