# Generated by Django 4.2.1 on 2023-06-08 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counselee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('type', models.CharField(choices=[('대인관계', '대인관계'), ('외로움', '외로움'), ('부정적 사고방식', '부정적 사고방식'), ('자존감 하락', '자존감 하락'), ('불면증', '불면증'), ('알코올 의존증', '알코올 의존증')], max_length=10)),
                ('Counselee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unlock2023.counselee', to_field='user_id')),
                ('Counselor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unlock2023.counselor', to_field='user_id')),
            ],
        ),
        migrations.AddField(
            model_name='counselor',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='unlock2023.user'),
        ),
        migrations.AddField(
            model_name='counselee',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='unlock2023.user'),
        ),
    ]
