# Generated by Django 4.2.1 on 2023-06-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlock2023', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='type',
            field=models.CharField(choices=[('대인관계', '대인관계'), ('외로움', '외로움'), ('부정적 사고방식', '부정적 사고방식'), ('자존감 하락', '자존감 하락'), ('불면증', '불면증'), ('알코올 의존증', '알코올 의존증'), ('기타', '기타')], max_length=10),
        ),
    ]
