# Generated by Django 4.2.1 on 2023-06-19 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_last_login"),
        ("unlock2023", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Counselor_list",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institution_name", models.CharField(max_length=50)),
                ("institution_address", models.CharField(max_length=100)),
                ("credit", models.CharField(max_length=30)),
                (
                    "c_id",
                    models.ForeignKey(
                        db_column="c_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.counselor",
                    ),
                ),
                (
                    "prof_field",
                    models.ForeignKey(
                        db_column="prof_field",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="unlock2023.counselingtype",
                    ),
                ),
            ],
        ),
    ]
