# Generated by Django 4.2.1 on 2023-06-16 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SelfCheck",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "public_yn",
                    models.CharField(
                        choices=[("y", "Yes"), ("n", "No")], default="n", max_length=1
                    ),
                ),
                ("video_url", models.URLField(null=True)),
                ("analysis_url", models.URLField(null=True)),
                (
                    "counselee_id",
                    models.ForeignKey(
                        db_column="counselee_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selfcheck",
                        to="accounts.counselee",
                    ),
                ),
            ],
        ),
    ]
