# Generated by Django 4.2.1 on 2023-06-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfcheck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfcheck',
            name='analysis_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='selfcheck',
            name='video_url',
            field=models.URLField(null=True),
        ),
    ]
