# Generated by Django 4.2.1 on 2023-06-18 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_counselee_userkey_alter_counselor_userkey"),
        ("selfcheck", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selfcheck",
            name="counselee_id",
            field=models.ForeignKey(
                db_column="counselee_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="selfcheck_id",
                to="accounts.counselee",
            ),
        ),
    ]
