# Generated by Django 4.2.1 on 2023-08-03 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_counselingtype_counselor_credit_and_more'),
        ('selfcheck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfcheck',
            name='counselee_id',
            field=models.ForeignKey(db_column='counselee_id', on_delete=django.db.models.deletion.CASCADE, related_name='selfcheck_id', to='accounts.counselee'),
        ),
    ]
